enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven(url = "https://jitpack.io")
        gradlePluginPortal()
    }
}

rootProject.name = "IvyWallet"
include(":app")
include(":feature:accounts")
include(":feature:balance")
include(":feature:budgets")
include(":feature:categories")
include(":feature:edit-transaction")
include(":feature:exchange-rates")
include(":feature:home")
include(":feature:import-data")
include(":feature:loans")
include(":feature:main")
include(":feature:piechart")
include(":feature:planned-payments")
include(":feature:reports")
include(":feature:search")
include(":feature:settings")
include(":feature:transactions")
include(":shared:base")
include(":shared:data:core")
include(":shared:data:core-testing")
include(":shared:data:model")
include(":shared:data:model-testing")
include(":shared:domain")
include(":shared:ui:core")
include(":shared:ui:navigation")
include(":temp:legacy-code")
include(":temp:old-design")
